export const mockBooths = [
  {
    id: 1,
    name: "Premium Corner Booth",
    description: "High-traffic corner location with excellent visibility",
    price: 5000,
    photo: "/premium-booth-corner.jpg",
    status: "available",
    addons: [
      { id: 1, name: "Extra Table", price: 200 },
      { id: 2, name: "LED Lighting", price: 300 },
      { id: 3, name: "WiFi Package", price: 150 },
    ],
    bookingRequests: [
      {
        id: 101,
        enterpriseName: "TechCorp Solutions",
        contactPerson: "John Smith",
        email: "john@techcorp.com",
        phone: "+1 (555) 123-4567",
        address: "123 Tech Street, San Francisco, CA 94105",
        registrationNumber: "TC-2024-001",
        requestedDate: "2024-12-15",
        duration: "3 days",
        boothSize: "10x10",
        numberOfStaff: 5,
        paymentMethod: "Bank Transfer",
        amount: 5000,
        paymentProof: "/bank-transfer-receipt.png",
        notes: "Interested in premium positioning",
      },
      {
        id: 102,
        enterpriseName: "Digital Innovations Inc",
        contactPerson: "Sarah Johnson",
        email: "sarah@digitalinnovations.com",
        phone: "+1 (555) 234-5678",
        address: "456 Innovation Ave, New York, NY 10001",
        registrationNumber: "DI-2024-002",
        requestedDate: "2024-12-15",
        duration: "3 days",
        boothSize: "10x10",
        numberOfStaff: 4,
        paymentMethod: "Cheque",
        amount: 5000,
        paymentProof: "/cheque-payment.jpg",
        notes: "First time exhibitor",
      },
    ],
  },
  {
    id: 2,
    name: "Standard Booth A",
    description: "Central location with good foot traffic",
    price: 3500,
    photo: "/standard-booth.jpg",
    status: "available",
    addons: [
      { id: 4, name: "Extra Table", price: 200 },
      { id: 5, name: "WiFi Package", price: 150 },
    ],
    bookingRequests: [
      {
        id: 103,
        enterpriseName: "Global Marketing Group",
        contactPerson: "Michael Chen",
        email: "michael@globalmarketing.com",
        phone: "+1 (555) 345-6789",
        address: "789 Marketing Blvd, Los Angeles, CA 90001",
        registrationNumber: "GM-2024-003",
        requestedDate: "2024-12-15",
        duration: "2 days",
        boothSize: "8x8",
        numberOfStaff: 3,
        paymentMethod: "Bank Transfer",
        amount: 3500,
        paymentProof: "/bank-transfer.png",
        notes: "Returning exhibitor",
      },
    ],
  },
  {
    id: 3,
    name: "Standard Booth B",
    description: "Mid-level location with moderate traffic",
    price: 3500,
    photo: "/standard-booth.jpg",
    status: "booked",
    addons: [{ id: 6, name: "Extra Table", price: 200 }],
    bookingRequests: [],
  },
  {
    id: 4,
    name: "Economy Booth A",
    description: "Budget-friendly option",
    price: 2000,
    photo: "/economy-booth.jpg",
    status: "available",
    addons: [],
    bookingRequests: [],
  },
  {
    id: 5,
    name: "Economy Booth B",
    description: "Budget-friendly option",
    price: 2000,
    photo: "/economy-booth.jpg",
    status: "available",
    addons: [],
    bookingRequests: [],
  },
  // Add more booths to reach 55 total
  ...Array.from({ length: 50 }, (_, i) => ({
    id: i + 6,
    name: `Booth ${String.fromCharCode(65 + (i % 26))}${Math.floor(i / 26) + 1}`,
    description: "Standard exhibition booth",
    price: Math.random() > 0.5 ? 3500 : 2000,
    photo: "/exhibition-booth.png",
    status: Math.random() > 0.7 ? "booked" : "available",
    addons: [],
    bookingRequests: [],
  })),
]
